# Generated by Django 4.2.28 on 2026-05-21 06:28

from django.db import migrations, models
import django.db.models.deletion
import files.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserStorageMetrics",
            fields=[
                (
                    "user_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "total_storage_used",
                    models.BigIntegerField(
                        default=0,
                        help_text="Bytes after deduplication (unique physical content per user).",
                    ),
                ),
                (
                    "original_storage_used",
                    models.BigIntegerField(
                        default=0,
                        help_text="Sum of logical file sizes as if every upload were stored separately.",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User storage metrics",
            },
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to=files.models.file_upload_path)),
                ("original_filename", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=100)),
                ("size", models.BigIntegerField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("user_id", models.CharField(db_index=True, max_length=255)),
                ("file_hash", models.CharField(db_index=True, max_length=64)),
                ("is_reference", models.BooleanField(default=False)),
                ("reference_count", models.PositiveIntegerField(default=1)),
                (
                    "original_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="files.file",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["user_id", "file_hash"],
                        name="files_file_user_id_da50a1_idx",
                    ),
                    models.Index(
                        fields=["user_id", "original_filename"],
                        name="files_file_user_id_160301_idx",
                    ),
                    models.Index(
                        fields=["user_id", "file_type"],
                        name="files_file_user_id_11f2e8_idx",
                    ),
                    models.Index(
                        fields=["user_id", "size"], name="files_file_user_id_891e6c_idx"
                    ),
                    models.Index(
                        fields=["user_id", "uploaded_at"],
                        name="files_file_user_id_0d661d_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="file",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_reference", False)),
                fields=("user_id", "file_hash"),
                name="unique_canonical_per_user_hash",
            ),
        ),
    ]
